jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Set up Google Cloud credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/keyfile.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/keyfile.json

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project your-project-id

    - name: Install dependencies
      run: npm install

    - name: Install BigQuery package
      run: npm install --save @google-cloud/bigquery

    - name: Install CORS and Body-Parser
      run: |
        npm install cors body-parser
